version: "3.9"
services:
  app:
    build: .
    container_name: inbox-steward
    restart: unless-stopped
    environment:
      APP_NAME: "Inbox Steward"
      LOG_LEVEL: "INFO"
      DATABASE_URL: "postgresql+psycopg2://inbox_steward:inbox_steward@db:5432/inbox_steward"
      IMAP_HOST: "imap.example.com"
      IMAP_PORT: 993
      IMAP_USERNAME: "user@example.com"
      IMAP_PASSWORD: "changeme"
      IMAP_MAILBOX: "INBOX"
      TIMEZONE: "America/Vancouver"
      POLL_INTERVAL_SECONDS: 120
      FULL_SORT_INTERVAL_MINUTES: 180
      OLLAMA_ENDPOINT: "http://ollama:11434"
      OLLAMA_MODEL: "mistral"
      HOME_ASSISTANT_BASE_URL: "http://homeassistant:8123"
      HOME_ASSISTANT_TOKEN: ""
      HOME_ASSISTANT_MOBILE_TARGET: "mobile_app_your_device"
      PDF_TEMP_DIR: "/data/pdfs"
    ports:
      - "${INBOX_STEWARD_PORT:-8000}:8000"
    volumes:
      - ./storage/pdfs:/data/pdfs
    depends_on:
      - db
    networks:
      - inbox-steward

  db:
    image: postgres:15-alpine
    container_name: inbox-steward-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: inbox_steward
      POSTGRES_PASSWORD: inbox_steward
      POSTGRES_DB: inbox_steward
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - inbox-steward

  redis:
    image: redis:7-alpine
    container_name: inbox-steward-redis
    restart: unless-stopped
    networks:
      - inbox-steward

networks:
  inbox-steward:
    driver: bridge

volumes:
  db-data:
